### ISSUE TITLE
页面滚动后，菜单显示位置不正确

### ISSUE THREAD

**Issue by xflxfl** [boenfu/vue-easycm#1]
![1](http://p943fvoyb.bkt.clouddn.com/o1.png)

![2](http://p943fvoyb.bkt.clouddn.com/o2.png)

**Comment by boenfu** [comment]
不好意思..疏忽了 
现在已经修复上传了
 把 .cm-container   position: absolute;改成   position: fixed; 就可以了
 或者重新安装
