### ISSUE TITLE
请教请教

### ISSUE THREAD

**Issue by hkwin** [boenfu/vue-easycm#2]
作者，你好，我是照着你的例子写的，但是每次我一右键那个按钮，那个菜单就闪一下就消失了，这是为什么呢？
![image](https://user-images.githubusercontent.com/12762712/40525119-d8ada9f2-6010-11e8-9e84-84a4671684a7.png)
![image](https://user-images.githubusercontent.com/12762712/40525121-e123c10c-6010-11e8-9fea-b4fc31544ac3.png)

**Comment by hkwin** [comment]
有没有可能是电脑系统的问题呢？我是MACOS的，打开你的那个Demo也有同样的问题

**Comment by boenfu** [comment]
this.$root.$on('easyAxis', (axis) => {
        if (axis.tag == this.tag){
            this.show = true
            this.axis = axis
        }
      })
      document.addEventListener('**mousedown**', () => {
          this.show = false
      }, **true**)

应该是这里的问题
之前触发隐藏着没考虑完善 
我自个用着没问题就过了... 囧囧
原因应该是
显示事件触发后同时触发了鼠标弹起事件  所以有可能出现你的情况
现在改成了捕获阶段的鼠标按下
已更新提交啦 你试试能行了不
